/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_session_groups_sessionGroups_list_result$schema = z.object({
  'assignments': z.array(z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
  'group': z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'source': z.string().readonly(),
  'kind': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
  'updatedAt': z.number().readonly(),
})).readonly(),
})

export const TYPERT = {
  package: 'dsh-session-groups',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-session-groups#sessionGroups/list',
      service: 'sessionGroups',
      namespace: 'sessionGroups',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-session-groups/types#SessionGroupSnapshot',
        schema: dsh_session_groups_sessionGroups_list_result$schema,
      },
      sourceLocation: {"file":"packages/dsh-session-groups/src/index.ts","line":77,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host sidecar service consumed by channel/provider plugins and the browser Remote.",
        "summary": "Host sidecar service consumed by channel/provider plugins and the browser Remote.",
        "tags": [],
        "jsDoc": "/** Host sidecar service consumed by channel/provider plugins and the browser Remote. */",
        "key": "sessionGroups",
        "exportName": "SessionGroupsService",
        "members": [
          {
            "kind": "method",
            "name": "assign",
            "signature": "async assign(sessionId: SessionId, descriptor: SessionGroupDescriptor): Promise<void>",
            "summary": "Attach one provider-owned communication origin to a Session.",
            "jsDoc": "/**\n * Attach one provider-owned communication origin to a Session. The legacy\n * sessionGroups name stays compatible and does not replace Workspace membership.\n * Identical assignments are no-ops; a changed title replaces the descriptor durably.\n */"
          },
          {
            "kind": "method",
            "name": "unassign",
            "signature": "async unassign(sessionId: SessionId): Promise<void>",
            "summary": "Remove one Session's communication-origin assignment; absence is already successful.",
            "jsDoc": "/** Remove one Session's communication-origin assignment; absence is already successful. */"
          },
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') list(): SessionGroupSnapshot",
            "summary": "Return the complete immutable source-assignment snapshot for the browser.",
            "jsDoc": "/** Return the complete immutable source-assignment snapshot for the browser. */"
          }
        ],
        "types": [
          {
            "name": "SessionGroupAssignment",
            "declaration": "export interface SessionGroupAssignment {\n    readonly sessionId: SessionId;\n    readonly group: SessionGroupDescriptor;\n    readonly updatedAt: number;\n}"
          },
          {
            "name": "SessionGroupDescriptor",
            "declaration": "export interface SessionGroupDescriptor {\n    readonly id: SessionGroupId;\n    readonly title: string;\n    readonly source: string;\n    readonly kind?: string;\n}"
          },
          {
            "name": "SessionGroupId",
            "declaration": "export type SessionGroupId = Branded<'SessionGroupId'>;"
          },
          {
            "name": "SessionGroupSnapshot",
            "declaration": "export interface SessionGroupSnapshot {\n    readonly assignments: readonly SessionGroupAssignment[];\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
