/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { SessionGroupSnapshot } from 'dsh-session-groups/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$73657373696f6e47726f757073 {
    list: () => Promise<RemoteResult<SessionGroupSnapshot>>
  }
  interface TypertRemoteMap {
    'sessionGroups/list': () => Promise<RemoteResult<SessionGroupSnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'sessionGroups': TypertRemoteNamespace$73657373696f6e47726f757073
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
